name: Kaleb Kloppe
favicon: null
layout_spectrum: 1
typography_spectrum: 0.93884
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#020b0f'
    - '#2e2c38'
    - '#aeaeae'
    - '#5a5a5a'
  brandStrength: 0
  lightness: 0.75
  saturation: 0.875
  rhythmicContrast: 0.5413706605322659
purpose: []
